name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: jpetrucciani/black-check@20.8b1
      - uses: isort/isort-action@v0.1.0
        with:
          configuration: "--profile black"
